// data.js – Offres fictives de logements étudiants à Saint-Louis (UGB)

const logements = [
  {
    id: 1,
    titre: "Chambre meublée – Cité Soprim",
    type: "Chambre",
    quartier: "Soprim",
    prix: 25000,
    distanceMin: 8,
    surface: 12,
    description: "Chambre individuelle meublée avec lit, bureau et armoire. Accès cuisine partagée et douche commune. Propriétaire très arrangeant.",
    equipements: ["Lit", "Bureau", "Armoire", "Cuisine partagée", "Eau courante"],
    contact: "77 123 45 67",
    disponible: true,
    badge: "Économique"
  },
  {
    id: 2,
    titre: "Studio indépendant – Sor",
    type: "Studio",
    quartier: "Sor",
    prix: 55000,
    distanceMin: 15,
    surface: 22,
    description: "Studio tout équipé avec coin cuisine, salle de bain privée et climatisation. Idéal pour un étudiant souhaitant son indépendance.",
    equipements: ["Climatisation", "Cuisine équipée", "Douche privée", "Réfrigérateur", "Wi-Fi"],
    contact: "76 456 78 90",
    disponible: true,
    badge: "Populaire"
  },
  {
    id: 3,
    titre: "Colocation – 3 chambres Dakar Dem Dikk",
    type: "Colocation",
    quartier: "Dakar Dem Dikk",
    prix: 20000,
    distanceMin: 5,
    surface: 14,
    description: "Chambre dans appartement partagé entre 3 étudiants. Ambiance studieuse garantie. Proche arrêt de bus et marché.",
    equipements: ["Cuisine partagée", "Salon commun", "Wi-Fi", "Sécurité"],
    contact: "70 987 65 43",
    disponible: true,
    badge: "Meilleur rapport"
  },
  {
    id: 4,
    titre: "Appartement F2 – Langue de Barbarie",
    type: "Appartement",
    quartier: "Langue de Barbarie",
    prix: 90000,
    distanceMin: 20,
    surface: 40,
    description: "Appartement F2 entièrement rénové. Vue partielle sur le fleuve. Idéal pour couple ou étudiant avec bourse confortable.",
    equipements: ["Climatisation", "Cuisine équipée", "2 pièces", "Eau chaude", "Parking"],
    contact: "33 961 22 33",
    disponible: false,
    badge: "Premium"
  },
  {
    id: 5,
    titre: "Chambre chez l'habitant – Ndiolofène",
    type: "Chambre",
    quartier: "Ndiolofène",
    prix: 18000,
    distanceMin: 12,
    surface: 10,
    description: "Chambre calme chez une famille sérieuse. Repas possible en supplément. Environnement sécurisé et familial.",
    equipements: ["Lit", "Ventilateur", "Accès eau", "Repas optionnel"],
    contact: "77 321 00 11",
    disponible: true,
    badge: "Économique"
  },
  {
    id: 6,
    titre: "Studio moderne – Médina Courses",
    type: "Studio",
    quartier: "Médina Courses",
    prix: 65000,
    distanceMin: 10,
    surface: 28,
    description: "Studio récemment construit avec finitions modernes. Très lumineux, balcon inclus. Connexion fibre disponible.",
    equipements: ["Balcon", "Fibre optique", "Climatisation", "Douche privée", "Cuisine neuve"],
    contact: "76 654 32 10",
    disponible: true,
    badge: "Nouveau"
  },
  {
    id: 7,
    titre: "Colocation – Quartier Nord",
    type: "Colocation",
    quartier: "Quartier Nord",
    prix: 22000,
    distanceMin: 7,
    surface: 13,
    description: "Chambre dans appartement de 4 étudiants en MIAGE et Droit. Bibliothèque commune, silence après 22h.",
    equipements: ["Bibliothèque commune", "Wi-Fi", "Cuisine équipée", "Eau courante"],
    contact: "78 111 22 33",
    disponible: true,
    badge: null
  },
  {
    id: 8,
    titre: "Appartement F3 – Guet Ndar",
    type: "Appartement",
    quartier: "Guet Ndar",
    prix: 115000,
    distanceMin: 25,
    surface: 65,
    description: "Grand appartement F3 pour 2 ou 3 étudiants. Terrasse avec vue sur la mer. Trajet en taxi 7-rapide conseillé.",
    equipements: ["Terrasse", "3 pièces", "Cuisine équipée", "Climatisation", "Douche privée"],
    contact: "33 962 44 55",
    disponible: true,
    badge: "Vue mer"
  },
  {
    id: 9,
    titre: "Chambre – Cité UGB (privée)",
    type: "Chambre",
    quartier: "Zone UGB",
    prix: 30000,
    distanceMin: 3,
    surface: 11,
    description: "Chambre en résidence privée juste à côté du campus. Idéale pour les premiers semestres. Gardien 24h/24.",
    equipements: ["Sécurité 24h", "Eau courante", "Ventilateur", "Bureau"],
    contact: "77 900 88 77",
    disponible: true,
    badge: "À 3 min du campus"
  },
  {
    id: 10,
    titre: "Studio – Pikine Saint-Louis",
    type: "Studio",
    quartier: "Pikine",
    prix: 40000,
    distanceMin: 18,
    surface: 20,
    description: "Studio simple et pratique dans quartier résidentiel calme. Proche marché et transports. Propriétaire disponible.",
    equipements: ["Cuisine équipée", "Douche privée", "Eau courante", "Ventilateur"],
    contact: "70 222 33 44",
    disponible: true,
    badge: null
  },
  {
    id: 11,
    titre: "Colocation mixte – Léona",
    type: "Colocation",
    quartier: "Léona",
    prix: 27000,
    distanceMin: 6,
    surface: 15,
    description: "Chambre dans bel appartement partagé de 3 personnes, mixte, atmosphère internationale. Proche cafétéria étudiante.",
    equipements: ["Wi-Fi haut débit", "Cuisine moderne", "Salon", "Eau chaude"],
    contact: "76 777 88 99",
    disponible: true,
    badge: "Coup de cœur"
  },
  {
    id: 12,
    titre: "Appartement F2 – Bango",
    type: "Appartement",
    quartier: "Bango",
    prix: 75000,
    distanceMin: 30,
    surface: 38,
    description: "Appartement spacieux dans zone calme. Idéal pour étudiant en thèse ou en stage. Garage inclus.",
    equipements: ["Garage", "Jardin", "Cuisine équipée", "Climatisation", "Douche privée"],
    contact: "77 444 55 66",
    disponible: false,
    badge: null
  }
];
